package com.example.rc_chat.Database;

public enum dbStatus {
    REGISTER_USER_EXISTS, REGISTER_SUCCESS, REGISTER_FAILED, REGISTER_ERROR,
    LOGIN_FAILED, LOGIN_SUCCESS, LOGIN_USER_NOT_FOUND, LOGIN_ERROR
}
